### PR TITLE
creating the members section with avatars inside the home page

### PR DESCRIPTION
**Pull request by adirkandel**
Resolving #38

### CODE REVIEW

**Review by RoyTennenbaum — APPROVED** [review]
😍 🥇

**Comment by itaim18** [comment]
As I looked at it this isn't responsive for mobile quite enough.
I have a few ideas on how to fix it and add a dash of glitter to it if desired🪩

**Comment by adirkandel** [comment]
> As I looked at it this isn't responsive for mobile quite enough. I have a few ideas on how to fix it and add a dash of glitter to it if desired🪩

@itaim18 let me know what is your suggestion 🙏

**Comment by itaim18** [comment]
# **Okay😬​**
- So, looking in, I would probably start with putting repeating style rules at the @layer components to get a better hold of their styles.
- Then would modify the text in order for it to not cut out on mobile.
- Then would see how to reuse the logic Of the circles to create this grid more elgenatlly. 
- In order to do it and add a bit more glitter to it, I probably would have created 4 flexed seperate rows with their unique data allowing them to move as long as the mouse is not hovering the current row.
## **Refs:**
- 1.
```css
.placeholderSize {
    @apply bg-gray-700 h-[65px] md:h-[100px];
  }
  .placeholderCircle {
    @apply placeholderSize rounded-[50px] overflow-hidden;
  }
```
- 2.
WhatsApp Image 2023-09-03 at 13 47 42 (1)

**Pull request merged**
