### PR TITLE
fix/footer to bottom

### PR DESCRIPTION
**Pull request by RuthwikReddy09**
Fixes : #63

### CODE REVIEW

**Comment by rotembarsela** [comment]
Nice PR, don't forget about responsive desgin

**Comment by RuthwikReddy09** [comment]
Thanks for the comment. 
It is responsive right?

**Review by RoyTennenbaum — CHANGES_REQUESTED** [review]
This is responsive and a good solution.

One thing I noticed is that the scrollbar still appears even though there is no content to scroll through. probably not the exact size in pixels :)

**Comment by RoyTennenbaum** [comment]
Oh and please reformat your files by the most recent fork - it seems to not be passing the formatting test

**Comment by RuthwikReddy09** [comment]
Done.
Could you please check if it is working now.

**Pull request closed without merging**
