### PR TITLE
navbar and darkmode provider

### PR DESCRIPTION
**Pull request by rotembarsela**
* added dark mode that supports tailwind using 'dark:' on className
* navbar design

### CODE REVIEW

**Comment by rotembarsela** [comment]
👍🏻

**Comment by RoyTennenbaum** [comment]
Good job @rotembarsela, I have a few small details to discuss with you about this pr, we should schedule a tiny meeting, 
please send me a pm on discord 🚀

**Review by RoyTennenbaum — COMMENTED** [review]
Good job @rotembarsela, I have a few small details to discuss with you about this pr, we should schedule a tiny meeting,
please send me a pm on discord 🚀

**Review by RoyTennenbaum — CHANGES_REQUESTED** [review]
**After talking privately this is my feedback:**
1. next-themes dependency is probably not neccecary but if possible to implement without it I would like you to do so.
2. use css-variables and create a more defined environment - using 'dark:' class several times in every element leads to major code duplications accross the entire app.

awaiting your next PR :)

**Comment by rotembarsela** [comment]
> **After talking privately this is my feedback:**
> 
> 1. next-themes dependency is probably not neccecary but if possible to implement without it I would like you to do so.
> 2. use css-variables and create a more defined environment - using 'dark:' class several times in every element leads to major code duplications accross the entire app.
> 
> awaiting your next PR :)

* I was looking for a clean solution instead of using next-themes, couldn't find a good apporach to do so, I used the @layer on globals.css to create a custom class, of course it can be abstracted more, depends on the needs

* dark: is part of tailwindcss (like :hover, :focus, etc....) - any idea how to implement it otherwise?

**Comment by RoyTennenbaum** [comment]
> * dark: is part of tailwindcss (like :hover, :focus, etc....) - any idea how to implement it otherwise?

correction: I did not mean it shouldn't be used, I meant it should be used more effectively, such as with creating a custom class, which you are already implementing :)

**Comment by rotembarsela** [comment]
> > * dark: is part of tailwindcss (like :hover, :focus, etc....) - any idea how to implement it otherwise?
> 
> correction: I did not mean it shouldn't be used, I meant it should be used more effectively, such as with creating a custom class, which you are already implementing :)

added them, almost finished, included header section - just hero banner mix with bg is left to do

**Review by RoyTennenbaum — APPROVED** [review]
Thank you Rotem, 
for adding both light/dark mode functionality and the title section as well.
there are minor responsivity and color issues which we'll solve later on, for now this PR is great!

**Pull request merged**
