### PR TITLE
Projects - "Filters"

### LINKED ISSUE #73: Create filters component on 'projects' page
### Description

relevant files:

components/Projects/FiltersBar/FiltersBar.tsx
components/Projects/FiltersBar/FilterDropdown.tsx
app/projects/page.tsx

### Screenshots

image

### Additional information

Further notes on [figma](https://www.figma.com/file/Ib05mHSvinzf9NNqIqftLR/Maakaf?type=design&node-id=51-508&mode=design&t=GyAJ58EvT8NxYioy-0)

### PR DESCRIPTION
**Pull request by rotembarsela**
Resolves #73 

* static data filters UI
* done

### CODE REVIEW

**Comment by rotembarsela** [comment]
@RoyTennenbaum, @adirkandel

**Comment by RoyTennenbaum** [comment]
@rotembarsela please sync your fork to the latest version, the folders were re-lowercased and we would be able to preview your pr once you do :)

**Comment by rotembarsela** [comment]
> @rotembarsela please sync your fork to the latest version, the folders were re-lowercased and we would be able to preview your pr once you do :)

I did a pull and synced the Fork, maybe I am missing something?

**Comment by RoyTennenbaum** [comment]
Please retry, the folders were corrupt :(
I replaced all route folders it was the easiest solution

**Comment by rotembarsela** [comment]
> Please retry, the folders were corrupt :( I replaced all route folders it was the easiest solution

done

**Review by RoyTennenbaum — APPROVED** [review]
This is amazing, stunningly accurate!

I understand this is not fully complete in order to allow other contributors to participate.
Merging :)

**Pull request merged**
