### PR TITLE
Feature/quote section

### PR DESCRIPTION
**Pull request by Etinger-Asaf**
Updated quote section.

### CODE REVIEW

**Review by RoyTennenbaum — APPROVED** [review]
LGTM

**Comment by RoyTennenbaum** [comment]
Hi, linting and formatting were bugged and recently were fixed.
Please re-submit this PR after pulling the latest project version and correcting conflicts (if any).

Sorry for the inconvenience

**Comment by RoyTennenbaum** [comment]
fixes #7

**Review by RoyTennenbaum — CHANGES_REQUESTED** [review]
thank you for dedicating yourself to the project - your component is looking great.

Improvements:
1. why are you using 'use theme' here? you may use only dark: class (darkmode has already been implemented in tailwind css)
2. notice the background does not change from black to white when switching modes.
3. heading classes are pre-defined in globals.css & tailwind.config, so there is no need for 'lg:text-2xl' and classes of the sort. just easily choosing the fitting h tag :)

**Comment by Etinger-Asaf** [comment]
I made changes according to your feedback.
If the background color on the light mode does need to change, halt the merge and let me know.
I'll wait for the Figma update and submit a new commit.

**Review by RoyTennenbaum — APPROVED** [review]
This is looking great! thank you for the commitment.

About the design, should there be changes we'll do those later on

**Pull request merged**
