### PR TITLE
Adding the `paths` component along with the set colors

### PR DESCRIPTION
**Pull request by itaim18**
Make sure to talk to me before deciding to close PRs for I could add commits according to changes you'd like to add,
as well about the css changes I commited to other files dor improving layout.

### CODE REVIEW

**Comment by rotembarsela** [comment]
> Make sure to talk to me before deciding to close PRs for I could add commits according to changes you'd like to add, as well about the css changes I commited to other files dor improving layout.

There is a custom class: darkmode-section, you can use for the section bg-color

**Comment by itaim18** [comment]
While this is true, you could see on the figma that this class wouldn't match the colors required for the paths' section

**Review by RoyTennenbaum — COMMENTED** [review]
Overall a very high quality PR!

One note: all colors should be used from the pre-defined color palette (in tailwind.config),
let's make this tiny change and submit this issue

**Review by RoyTennenbaum — APPROVED** [review]
Nice! that marks issue #9 closed!

**Pull request merged**
