### PR TITLE
Adding Framer-Motion package and animating BeOurFriends.tsx

### PR DESCRIPTION
**Pull request by develad**
A suggestion to add an animation library for fun user interactions

### CODE REVIEW

**Review by RoyTennenbaum — COMMENTED** [review]
We do have plans for the future in terms of animation and it is a great library!

You have a minor conflict, I merged a pr that changes the paths component a bit, please resolve it and I'll merge 🙏

**Comment by develad** [comment]
@RoyTennenbaum 
Try it out now :)
[87f065c](https://github.com/develad/maakaf-website/commit/87f065c543702d477ff7ade3491faae1fdd0ea83)

**Review by RoyTennenbaum — APPROVED** [review]
Love these animations, very well done!

The small fixes were indeed necessary, I am merging everything but on a small note - please make sure that a pr only handles one issue, small fixes can come in a different pr.
It will make for an easier time to review and merge, and is best practice for open source development 💯

**Comment by develad** [comment]
> Love these animations, very well done!
> 
> The small fixes were indeed necessary, I am merging everything but on a small note - please make sure that a pr only handles one issue, small fixes can come in a different pr. It will make for an easier time to review and merge, and is best practice for open source development 💯

Fully noted... Thanks for the review and merging! 🚀

**Pull request merged**
