### PR TITLE
Adjust the svg and the titles to the right size

### PR DESCRIPTION
**Pull request by oshri1997**
Adjust the svg and the titles to the right size

### CODE REVIEW

**Review by RoyTennenbaum — CHANGES_REQUESTED** [review]
much better than how it was originally!

I do think you used the exact values I specified for width and height but remember they only fit the screen size on figma - on wider screens the image is still too small.

About text sizes - those are already predefined in globals.css, just using the right h tag and not messing around should be sufficient.

Tell me how it goes 🥇

**Comment by oshri1997** [comment]
change the width of  the svg to more flexible for wider screens  
waiting for your  review.

**Review by RoyTennenbaum — CHANGES_REQUESTED** [review]
Hi Oshri, hopefully these screenshots will assist my review:

image
here the image is too small - there is too much space between it and the title

image
It seems the image is being affected by the viewport too much - the wider it is and the lower it is, the svg seems to get smaller and smaller.

I don't think it's a matter of rewriting the whole thing, but it should be adjusted still. mobile view is perfect though :)

**Comment by RoyTennenbaum** [comment]
@oshri1997 apologies for the delay, 
I did not mean the max-width attribute, we don't want to make it ultra-wide so it would fit any screen.

What we DO want is an image that would not be affected by the viewport, it should not resize when the user's screen is very low and/or wide

**Comment by oshri1997** [comment]
I updated the code :)

**Comment by oshri1997** [comment]
@adirkandel  @RoyTennenbaum 
Waiting for your review.

**Review by RoyTennenbaum — APPROVED** [review]
I was out for a while since I had a large assignment due @oshri1997 
This PR is great, the main issue is resolved so I will merge it and thanks for contributing :)

An issue with clipping with the quote section still remains (that will be a different issue so no worries)

**Pull request merged**
