### PR TITLE
Design and navigation fix

### PR DESCRIPTION
**Pull request by nitzanto**
Issue #84
* Fixed the image responsive had to remove the xl:h-[90vh] and lg:mt-[1.2rem] classes since they were causing issues with responsiveness.  

Fixed issue  #78 
* Added Missing Navigation Links In The Footer
* Fixed Navigation Links in the rest of the pages

### CODE REVIEW

**Comment by nitzanto** [comment]
@RoyTennenbaum Waiting for your review, thanks ;)

**Review by RoyTennenbaum — CHANGES_REQUESTED** [review]
Thanks for taking your time to contribute :)

Please notice all links should be lowercase.

Additionally, the SVG did improve, but I am still not completely satisfied as the responsivity is a bit off. if you could find the cause it'll be a pleasure...
Attaching screenshots:
image it is not attached to top.

image It is weirdly affected by the viewport.

**Comment by nitzanto** [comment]
> Thanks for taking your time to contribute :)
> 
> Please notice all links should be lowercase.
> 
> Additionally, the SVG did improve, but I am still not completely satisfied as the responsivity is a bit off. if you could find the cause it'll be a pleasure... Attaching screenshots: image it is not attached to top.
> 
> image It is weirdly affected by the viewport.

Hey Roy,

Regarding the links, all of the routes within the app folder start with a big letter therefore I had to change it because before it would navigate to a 404 page.

I think the solution to this could be done by changing the folder names to lowercase or creating a util function (component) which could take care of this issue, however I believe it would make stuff more complex.

About the design, I am a bit confused is the image supposed to be behind the text, next to the text? I am trying to understand what's the desired result, thank you :)

**Comment by RoyTennenbaum** [comment]
@nitzanto not sure if you noticed, but folder names were changed, not sure if this pr is entirely relevant.
please make the changes accordingly and re-submit :)

**Comment by RoyTennenbaum** [comment]
I am closing this pr as not relevant... no worries @nitzanto  please try a different issue if you'd like there are several others as of today :)

**Pull request closed without merging**
