### PR TITLE
Sidebar implementation on Mobile

### LINKED ISSUE #48: Sidebar component
### Description

create a page called Sidebar.tsx in 'components/Header' folder.

### Screenshots

_No response_

### Additional information

Notice spacing, margins, paddings, colors etc.
[all here](https://www.figma.com/file/Ib05mHSvinzf9NNqIqftLR/Maakaf?type=design&node-id=51-508&mode=design&t=vgLHgBDYB4WgsOG5-0)

### PR DESCRIPTION
**Pull request by rotembarsela**
* added sidebar with transition using tailwind only
* adjusted darkmode component so it will be accessible using TAB and SPACE on it
* added 2 hooks:
- useMediaQuery: to check the current screen size and render different components based on that,
- useFocusTrap: to trap an component and block TABS navigation outside of it so it become accessible

- not done yet 

fixes #48

### CODE REVIEW

**Comment by rotembarsela** [comment]
@RoyTennenbaum Why vercel deployment has been failed?

**Comment by RoyTennenbaum** [comment]
Hi, linting and formatting were bugged and recently were fixed.
Please re-submit this PR after pulling the latest project version and correcting conflicts (if any).

Sorry for the inconvenience

**Comment by rotembarsela** [comment]
> Hi, linting and formatting were bugged and recently were fixed. Please re-submit this PR after pulling the latest project version and correcting conflicts (if any).
> 
> Sorry for the inconvenience

done

**Review by RoyTennenbaum — APPROVED** [review]
LGTM

**Pull request merged**
