### PR TITLE
Creating about page

### PR DESCRIPTION
**Pull request by adirkandel**
closes: #45 & #46

### CODE REVIEW

**Review by RoyTennenbaum — COMMENTED** [review]
Extremely well done on all aspects - working well, responsive & beautiful carousel and about page :)

One thing I did not understand is why was the husky pre-commit removed, your PR will be merged afterwards

**Comment by rotembarsela** [comment]
Nice PR, if i may add, you forgot the "Maakaf" logo on the background (left side)

**Comment by adirkandel** [comment]
> One thing I did not understand is why was the husky pre-commit removed, your PR will be merged afterwards

@RoyTennenbaum looks like it has something to do with issue described [in here](https://stackoverflow.com/questions/1580596/how-do-i-make-git-ignore-file-mode-chmod-changes) because i did change the file permission to be able to execute it but didn't add any changes.
If this is the only thing that left and you approve this PR i suggest to merge it and if the husky file will still be removed we can add it again easily. WDYT?

**Comment by adirkandel** [comment]
> Nice PR, if i may add, you forgot the "Maakaf" logo on the background (left side)

@rotembarsela Great catch, thank you! I'm on it.

**Review by RoyTennenbaum — APPROVED** [review]
Beautiful about page 💯 

I resolved a minor conflict in order to merge it properly :)
Your efforts are much appreciated

**Pull request merged**
